### ISSUE TITLE
Is adding z-index in #mobile-debug a good ideal ?

### ISSUE THREAD

**Issue by inkcarve** [muggy8/mobile-debug#1]
This project is useful , light and awesome , but if there are elements with z-index, the mobile-debug looks transparent , as shown below:
<img src="https://image.ibb.co/eVvbqc/mobile_inspector.png"/>

Thanks.

**Comment by muggy8** [comment]
hmm that is an issue. I'm not quite sure how to solve since a lot of people use really large Z-indexes for stuff that "should always be on top" so if I set my Z-index to 10000 someone's going to use a bigger Z-Index. I'll have to play around with solutions for a bit to see if I can come up with something for this :)

as a temporary solution for now, you can use the non-minfied version which uses static class/ids so you can add a rule in your own CSS to elevate the debugger #mobile-debug {z-index: 9001}

thanks :D!

**Comment by muggy8** [comment]
Alright I have added a way for you to specify the z-index of the entire debugger (and various other properties) to allow you to elevate the debugger to a higher z-index if needs be (or lower if you're trying to hide it). Hopefully this helps
